import assert from 'node:assert/strict';
import { readFile, mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';
const base = process.env.EVAL_BASE_URL ?? 'http://localhost:3000';
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
try {
 const page = await context.newPage(); const errors = [];
 page.on('pageerror', error => errors.push(error.message));
 await page.goto(base);
 await page.getByRole('heading', { name: 'Ask your documents', exact: true }).waitFor();
 await page.waitForFunction(() => !document.querySelector('.upload-button').disabled);
 await page.keyboard.press('Tab');
 assert.equal(await page.evaluate(() => document.activeElement.textContent.trim()), 'Upload document');
 assert.equal(await page.evaluate(() => getComputedStyle(document.activeElement).outlineWidth), '3px');
 const handbook = await readFile('fixtures/handbook.md');
 const uploaded = page.waitForResponse(response => response.url().endsWith('/api/documents') && response.request().method() === 'POST', { timeout: 120_000 });
 await page.locator('#document-upload').setInputFiles({ name: 'browser-handbook.md', mimeType: 'text/markdown', buffer: handbook });
 const upload = await uploaded;
 assert.equal(upload.status(), 201); const doc = (await upload.json()).document;
 await page.getByRole('checkbox').waitFor();
 const question = page.getByLabel('What would you like to know?');
 await question.fill('What do I need to do before requesting reimbursement?');
 const answered = page.waitForResponse(response => response.url().endsWith('/api/ask'), { timeout: 120_000 });
 await page.getByRole('button', { name: 'Ask', exact: true }).click();
 const answer = await (await answered).json();
 assert.equal(answer.status, 'answered'); assert.match(answer.answer, /approval/i); assert.match(answer.answer, /receipt/i);
 const summary = page.locator('summary').first();
 await summary.waitFor(); await summary.focus(); await page.keyboard.press('Enter');
 assert.equal(await page.locator('details').first().evaluate(element => element.open), true);
 assert.equal(await page.locator('blockquote').first().textContent(), answer.citations[0].excerpt);
 assert.ok(handbook.toString().includes(answer.citations[0].excerpt));
 const cookies = await context.cookies(); const session = cookies.find(cookie => cookie.name === 'document_qa_workspace');
 assert.ok(session?.httpOnly); assert.equal(session.sameSite, 'Lax');
 if (base.startsWith('https:')) assert.equal(session.secure, true);
 await mkdir('.impeccable/review', { recursive: true });
 await page.screenshot({ path: '.impeccable/review/desktop.png', fullPage: true });
 await page.setViewportSize({ width: 390, height: 844 });
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
 const panels = await page.locator('.workspace-panels').evaluate(element => getComputedStyle(element).gridTemplateColumns);
 assert.equal(panels.split(' ').length, 1);
 await page.screenshot({ path: '.impeccable/review/mobile.png', fullPage: true });
 await page.reload(); await page.getByRole('checkbox').waitFor();
 assert.equal(await page.getByRole('checkbox').count(), 1);
 const outsider = await browser.newContext();
 try {
  assert.deepEqual((await (await outsider.request.get(base + '/api/documents')).json()).documents, []);
  const denied = await outsider.request.post(base + '/api/ask', { headers: { Origin: base }, data: { question: 'Policy?', documentIds: [doc.id], history: [] } });
  assert.equal(denied.status(), 404); assert.equal((await denied.json()).error.code, 'DOCUMENT_NOT_FOUND');
 } finally { await outsider.close(); }
 await question.fill('What is the dental insurance annual deductible?');
 await page.route('**/api/ask', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'GUARD_UNAVAILABLE', message: 'A required safety check is unavailable. Try again.', retryable: true }, requestId: 'browser-outage-check' }) }));
 await page.getByRole('button', { name: 'Ask', exact: true }).click();
 await page.getByRole('button', { name: 'Try again', exact: true }).waitFor();
 assert.equal(await question.inputValue(), 'What is the dental insurance annual deductible?');
 await page.unroute('**/api/ask');
 const retry = page.waitForResponse(response => response.url().endsWith('/api/ask'), { timeout: 120_000 });
 await page.getByRole('button', { name: 'Try again', exact: true }).click();
 assert.equal((await (await retry).json()).status, 'insufficient_evidence');
 await page.getByRole('button', { name: 'Start new conversation', exact: true }).click();
 assert.equal(await question.inputValue(), ''); assert.equal(await page.getByRole('checkbox').count(), 1);
 assert.deepEqual(errors, []);
 console.log(JSON.stringify({ base, passed: true, documentId: doc.id, checks: ['live browser upload/answer/exact source', 'keyboard focus/source disclosure', 'desktop/mobile and no overflow', 'refresh persistence', 'cookie flags', 'cross-session API denial', 'simulated guard outage preserves input and live retry abstains', 'conversation reset keeps documents'] }, null, 2));
} finally { await context.close(); await browser.close(); }
